### ISSUE TITLE
Browsing Items by category

### ISSUE THREAD

**Issue by dshinzie** [bermannoah/check-please#3]
Background: I have two categories with titles and each has two different items assigned
    As a visitor
    When I visit "/:CATEGORY_NAME"
    I see all items assigned to that category

**Comment by bermannoah** [comment]
1. Create migration for categories table
2. Each category table will have: a name
3. Categories have many menu items, menu items belong to a category
4. Make a view page where you see categories listed...
5. ...and then a show page, where you see items in individual category.
